### ISSUE TITLE
Provide JSON option for consumers

### ISSUE THREAD

**Issue by benschinn** [mxenabled/mx-design-tokens#12]
It would be great if there was a script to provide a way for consumers to generate JSON file in their project. E.g. a non-js application may want to consume the token values from a JSON file. 

Happy to open a PR.

**Comment by brianrclay** [comment]
I think this is a good idea. We are bound to run into issues where applications will need to create tokens specifically for their application. For example, MoneyMap needs to create a pieChartBGColor token. That's not something we'll want in Kyper tokens so they will need to have app-level tokens.

This might be a separate issue, but I think there is some overlap here.

**Comment by jgerlach** [comment]
Can't you just import the buildTheme function and then add on to the json object?

**Comment by jgerlach** [comment]
Wouldn't that script be language specific?

**Comment by benschinn** [comment]
I am not sure if the language of the script is the concern here. It could be though, and if it was it could be a binary executable that can be run anywhere.

I opened the issue to mainly see what others thought about having a JSON output be outside of development and be available for consumers. It sounds like there may be benefit to non-js apps and js apps.

**Comment by benschinn** [comment]
Maybe we don't need a script at all, we could just ship the package with the JSON output?

**Comment by jgerlach** [comment]
I think you used to be able to do that

**Comment by benschinn** [comment]
@phantomxc are there any issues with adding `json` directory in `files` array in `package.json`? Although I don't know that would solve the problem @brianrclay surfaced.

**Comment by phantomxc** [comment]
If you want to consume the standard themes available, it's not a problem.
