### ISSUE TITLE
Consistency in using units in token values

### ISSUE THREAD

**Issue by benschinn** [mxenabled/mx-design-tokens#31]
In the private docs repo, we are converting the json tokens to scss. I noticed that some of the token values e.g. [font sizes](https://github.com/mxenabled/mx-design-tokens/blob/master/docs/tokens.md#fontsize) are just integers, and then some values e.g. [line height](https://github.com/mxenabled/mx-design-tokens/blob/master/docs/tokens.md#lineheight) are values with the unit included.

Can it be assumed we are using px as unit across the tokens? If that is the case, we might want consistency in including or not including units.

If including and excluding units in values was intentional, I'd love to know the reason behind it.

@phantomxc @jgerlach @brianrclay

**Comment by brianrclay** [comment]
The reason for the inconsistency is that we are trying to support react native as much as we can. @phantomxc would have more details. I would assume that we are ok to remove `px` from all the tokens but there is probably a good argument against that.

**Comment by phantomxc** [comment]
Yes, we want to support React Native and also Helios builds in the future. So we really have to think beyond just CSS values. As for your example, line height actually requires the pixel definition in React.

One of the ways I thought we could handle some of these weird values that don't really mix well was by providing a "target" to the build function. You can follow that around starting here: https://github.com/mxenabled/mx-design-tokens/blob/master/src/index.js#L10

and specifically see what we're doing for line height here: https://github.com/mxenabled/mx-design-tokens/blob/master/src/tokens/core.js#L96

**Comment by phantomxc** [comment]
Another note: These values haven't been flushed out for all the builds.

https://github.com/mxenabled/mx-design-tokens/blob/master/src/tokens/core.js#L64

**Comment by run-time** [comment]
the standard we are using is this:

- the values work as-is in a **React css json object** `light.json` and `dark.json` generate without cleansing rules
- store values in as few characters as possible (`4` instead of `"4px"`)
- have every other export type be responsible for cleansing the values (adding `px` or `ms` for `css`, putting quotes around things for `scss`, etc.)
