### ISSUE TITLE
Add z-index values to the tokens

### ISSUE THREAD

**Issue by taytestokes** [mxenabled/mx-design-tokens#37]
Currently, there aren't any specific values to apply to the z-index position of an element. I'm not exactly sure what values should be used, but I do think it would be useful to have.

**Comment by taytestokes** [comment]
@phantomxc @brianrclay

**Comment by TayteStokes** [comment]
It was brought up that this could be a good design to follow.

![Uploading image.png…]()

**Comment by taytestokes** [comment]
It was mentioned that this could be a good design to follow for the values.

![image](https://user-images.githubusercontent.com/35533279/84791698-36fee200-afb0-11ea-9915-30554b137a15.png)

**Comment by run-time** [comment]
thanks for the info Tayte. We've looked into this and have a first version of zIndex tokens to use starting in `10.0.0-rc.1`
