### ISSUE TITLE
Add ability to generate scss files from the tokens

### ISSUE THREAD

**Issue by sambev** [mxenabled/mx-design-tokens#63]
Add a script to generate a scss file that has the variables and then build out built in classes for buttons, inputs, etc.

cc @jgerlach @cerinman @run-time

**Comment by run-time** [comment]
I've completed this task in a fork of the code but don't have write permissions to push it here

**Comment by jgerlach** [comment]
I see that you are generating `scss` and `css` files, but how would you go about importing them into your project?

**Comment by run-time** [comment]
this has been implemented and working
